#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /usr/share/ngnix/html/index.html
fill="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "/# only/ i $fill" /etc/nginx/sites-available/default
sudo service nginx restart
