#!/usr/bin/env bash
# Installs and configures HAproxy on server

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.\*
echo "
frontend lb
	bind *:80
	mode http
	default_backend servers
	
backend servers
	mode http
	balance roundrobin
	server 221499-web-01 100.25.48.61:80 check
	server 221499-web-02 52.3.245.122:80 check" >> /etc/haproxy/haproxy.cfg
	service haproxy restart
